<?php
?>
<h1 class="ttl_general">LEGAL NOTICE</h1>
<p>In compliance with Law 34/2002, of July 11, Services of the Information Society and Electronic Commerce (LSSI-CE), PHARMALINK SL, trade name YSANA, informs that it owns the website WWW.YSANA.ES. In accordance with the requirement of article 10 of the Law, PHARMALINK SL informs of the following information:</p>
<p>The owner of this website is PHARMALINK SL, with CIF B62152335 and registered office at AV. UNIVERSITAT AUTÒNOMA, 13-PARC TECNOLÒGIC 08290, CERDANYOLA DEL VALLES (BARCELONA), registered in the Mercantile Register, in volume 37882 folio 23 sheet B-210706 and registration 25 The email address of contact with the company is: info@ysana.es. </p>

<h1>User and responsibilities regime</h1>
<p>The navigation, access and use by the website of PHARMALINK SL confers the condition of user, by which they are accepted, from browsing the website of PHARMALINK SL, all the conditions of use here established without prejudice to the application of the corresponding regulations of mandatory legal compliance.</p>
<p>The website of PHARMALINK SL provides a great diversity of information, services and data. The user assumes responsibility for the correct use of the website. This responsibility will extend to:</p>
<ul>
    <li>The veracity and legality of the information provided by the user in the forms extended by PHARMALINK SL for access to certain content or services offered by the web.</li>
    <li>The use of the information, services and data offered by PHARMALINK SL contrary to the provisions of these conditions, the Law, morality, good customs or public order, or that in any other way may imply an infringement of the rights of third parties or the same functioning of the website.</li>
</ul>
<h1>Link policy and liability exemptions</h1>
<p>PHARMALINK SL is not responsible for the content of the websites that the user can access through the links established on its website and declares that in no case will proceed to examine or exercise any type of control over the content of other sites of the network. Likewise, it will not guarantee the technical availability, accuracy, veracity, validity or legality of sites external to your property that can be accessed through the links.</p>
<p>PHARMALINK SL declares to have adopted all the necessary measures to avoid any damage to the users of its website, which may arise from browsing its website. Consequently, PHARMALINK SL is not responsible, in any case, for any damages that the user may suffer from browsing the Internet.</p>
<h1>Modifications</h1>
<p>PHARMALINK SL reserves the right to make the modifications it deems appropriate, without prior notice, in the content of its website. Both, regarding the contents of the website, and in the conditions of use thereof. Such modifications may be made through its website by any admissible form in law and shall be binding during the time they are published on the web and until they are validly modified by subsequent ones.</p>
<h1>Data Protection</h1>
<p>In accordance with the provisions of current regulations on Personal Data Protection, we inform you that your data will be incorporated into the treatment system owned by PHARMALINK SL with CIF B62152335 and registered office located at AV. UNIVERSITAT AUTÒNOMA, 13-PARC TECNOLÒGIC 08290, CERDANYOLA DEL VALLES (BARCELONA), with the purpose of facilitating, expediting and fulfilling the commitments established between both parties. In compliance with current regulations, PHARMALINK SL informs that the data will be kept for the period strictly necessary to comply with the precepts mentioned above.</p>
<p>PHARMALINK SL informs that it will proceed to treat the data in a lawful, loyal, transparent, adequate, pertinent, limited, exact and updated way. That is why PHARMALINK SL undertakes to adopt all reasonable measures so that these are suppressed or rectified without delay when they are inaccurate.</p>
<p>In accordance with the provisions of article 32 of Regulation (EU) 2016/679 of the European Parliament and of the Council, of April 27, 2016, concerning the protection of natural persons with regard to the processing of personal data and the free circulation of these data and by repealing Directive 95/46 / CE, PHARMALINK SL undertakes to adopt the necessary technical and organizational measures, according to the level of risks that accompany the treatments carried out by them and indicated in the section of the terms and conditions of use, so as to guarantee their integrity, confidentiality and availability.</p>
<p>Likewise, PHARMALINK SL informs that if the User enters data in the forms of the websites of third parties, the latter will be responsible for the personal data, and who must adopt the technical measures described in the section of the present Terms and conditions of use.</p>
<p>PHARMALINK SL informs about the possibility of exercising the rights of access, rectification, limitation of treatment, deletion, portability and opposition to the treatment, of which the User has and that may be exercised before PHARMALINK SL. According to Chapter III of the RGPD, you must consider the following nuances:</p>

<p>- <strong>Right of Access:</strong> It is the user's right to obtain information about their specific personal data and the treatment that has been carried out or made, as well as the information available about the origin of said data and the communications made or planned thereof.</p>
<p>- <strong>Right of Rectification:</strong> It is the right of the affected party to modify the data that prove to be inaccurate or incomplete. You can only be satisfied in relation to information that is under the control of PHARMALINK SL, for example, remove comments posted on the page itself, images or web content where personal data of the user are recorded.</p>
<p>- <strong>Right to the Limitation of treatment:</strong> It is the right to limit the treatment ends originally envisaged by the controller.</p>
<p>- <strong>Right of Suppression:</strong> It is the right to suppress the personal data of the user, except as provided in the RGPD itself or in other applicable regulations that determine the obligation to preserve them, in a timely manner.</p>
<p>- <strong>Portability right:</strong> The right to receive personal data that the user has provided, in a structured format, for common use and mechanical reading, and to transmit them to another person in charge.</p>
<p>- <strong>Right of Opposition:</strong> It is the right of the user not to carry out the processing of their personal data or to cease the treatment thereof by PHARMALINK SL.</p>
<p>In accordance with the rights conferred by the current regulations on data protection may exercise the rights of access, rectification, limitation of treatment, deletion, portability and opposition to the processing of their personal data and consent given for the treatment of them, directing your request to the postal address indicated above or to the email info@ysana.es. </p>
<p>You can go to the competent Control Authority to present the claim that you consider appropriate.</p>

<h1>Intellectual and industrial property</h1>

<p>PHARMALINK SL by itself or as an assignee, is the owner of all the intellectual and industrial property rights of its web page, as well as the elements contained in it (for example, images, sound, audio, video, software or texts) ; trademarks or logos, combinations of colours, structure and design, selection of used materials, computer programs necessary for its operation, access and use, etc.), ownership of PHARMALINK SL. They will, therefore, works protected as intellectual property by the Spanish legal system, being applicable both Spanish and EU regulations in this field, as well as international treaties related to the subject and signed by Spain.</p>
<p>All rights reserved. Under the provisions of the Law on Intellectual Property, the reproduction, distribution and public communication, including its method of making available, all or part of the contents of this web page, for commercial purposes, are expressly prohibited. in any support and by any technical means, without the authorization of PHARMALINK SL.</p>
<p>The user agrees to respect the rights of Intellectual and Industrial Property owned by PHARMALINK SL. You can visualize the elements of the portal and even print them, copy them and store them on your computer's hard drive or on any other physical medium, as long as it is solely and exclusively for your personal and private use. The user must refrain from deleting, altering, evading or manipulating any protection device or security system that was installed on the pages of PHARMALINK SL.</p>
<p>Legal actions, applicable legislation and jurisdiction</p>
<p>PHARMALINK SL also reserves the right to file civil or criminal actions it deems appropriate for the improper use of its website and content, or for the breach of these conditions.</p>
<p>The relationship between the user and the provider will be governed by the regulations in force and applicable in Spanish territory. If any dispute arises, the parties may submit their disputes to arbitration or go to the ordinary jurisdiction, complying with the rules on jurisdiction and competence in this regard. PHARMALINK SL has its address in BARCELONA, Spain.</p>

