<?php
?>
<h1 class="ttl_general">AVISO LEGAL</h1>
<p>En cumplimiento de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE), PHARMALINK SL, nombre comercial YSANA, informa que es titular del sitio web WWW.YSANA.ES. De acuerdo con la exigencia del artículo 10 de la citada Ley, PHARMALINK SL informa de los siguientes datos: </p>
<p>El titular de este sitio web es PHARMALINK SL, con CIF B62152335 y domicilio social en AV. UNIVERSITAT AUTÒNOMA, 13-PARC TECNOLÒGIC 08290, CERDANYOLA DEL VALLES (BARCELONA), inscrita en el Registro Mercantil, en el tomo 37882 folio 23 hoja B-210706 e inscripción 25 La dirección de correo electrónico de contacto con la empresa es: info@ysana.es.</p>

<h1>Usuario y régimen de responsabilidades </h1>
<p>La navegación, acceso y uso por el sitio web de PHARMALINK SL confiere la condición de usuario, por la que se aceptan, desde la navegación por el sitio web de PHARMALINK SL, todas las condiciones de uso aquí establecidas sin perjuicio de la aplicación de la correspondiente normativa de obligado cumplimiento legal según el caso. </p>
<p>El sitio web de PHARMALINK SL proporciona gran diversidad de información, servicios y datos. El usuario asume su responsabilidad en el uso correcto del sitio web. Esta responsabilidad se extenderá a: </p>
<ul>
    <li>La veracidad y licitud de las informaciones aportadas por el usuario en los formularios extendidos por PHARMALINK SL para el acceso a ciertos contenidos o servicios ofrecidos por el web.</li>
    <li>El uso de la información, servicios y datos ofrecidos por PHARMALINK SL contrariamente a lo dispuesto por las presentes condiciones, la Ley, la moral, las buenas costumbres o el orden público, o que de cualquier otro modo puedan suponer lesión de los derechos de terceros o del mismo funcionamiento del sitio web.</li>
</ul>
<h1>Política de enlaces y exenciones de responsabilidad </h1>
<p>PHARMALINK SL no se hace responsable del contenido de los sitios web a los que el usuario pueda acceder a través de los enlaces establecidos en su sitio web y declara que en ningún caso procederá a examinar o ejercitar ningún tipo de control sobre el contenido de otros sitios de la red. Asimismo, tampoco garantizará la disponibilidad técnica, exactitud, veracidad, validez o legalidad de sitios ajenos a su propiedad a los que se pueda acceder por medio de los enlaces. </p>
<p>PHARMALINK SL declara haber adoptado todas las medidas necesarias para evitar cualquier daño a los usuarios de su sitio web, que pudieran derivarse de la navegación por su sitio web. En consecuencia, PHARMALINK SL no se hace responsable, en ningún caso, de los eventuales daños que por la navegación por Internet pudiera sufrir el usuario.</p>
<h1>Modificaciones</h1>
<p>PHARMALINK SL se reserva el derecho a realizar las modificaciones que considere oportunas, sin aviso previo, en el contenido de su sitio web. Tanto en lo referente a los contenidos del sitio web, como en las condiciones de uso de este. Dichas modificaciones podrán realizarse a través de su sitio web por cualquier forma admisible en derecho y serán de obligado cumplimiento durante el tiempo en que se encuentren publicadas en la web y hasta que no sean modificadas válidamente por otras posteriores. </p>
<h1>Protección de datos</h1>
<p>De conformidad con lo establecido en la normativa vigente en Protección de Datos de Carácter Personal, le informamos que sus datos serán incorporados al sistema de tratamiento titularidad de PHARMALINK SL con CIF B62152335 y domicilio social sito en AV. UNIVERSITAT AUTÒNOMA, 13PARC TECNOLÒGIC 08290, CERDANYOLA DEL VALLES (BARCELONA), con la finalidad de poder facilitar, agilizar y cumplir los compromisos establecidos entre ambas partes. En cumplimiento con la normativa vigente, PHARMALINK SL informa que los datos serán conservados durante el plazo estrictamente necesario para cumplir con los preceptos mencionados con anterioridad. </p>
<p>PHARMALINK SL informa que procederá a tratar los datos de manera lícita, leal, transparente, adecuada, pertinente, limitada, exacta y actualizada. Es por ello que PHARMALINK SL se compromete a adoptar todas las medidas razonables para que estos se supriman o rectifiquen sin dilación cuando sean inexactos. </p>
<p>De acuerdo con lo establecido por el artículo 32 del Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y a la libre circulación de estos datos y por el que se deroga la Directiva 95/46/CE, PHARMALINK SL se compromete a adoptar las medidas técnicas y organizativas necesarias, acorde al nivel de riesgos que acompañan los tratamientos realizados por éstas e indicados en el apartado de los términos y condiciones de uso, de forma que garanticen su integridad, confidencialidad y disponibilidad. </p>
<p>Asimismo, PHARMALINK SL informa que en el caso que el Usuario introduzca datos en los formularios de los sitios web de terceros, serán estos últimos los responsables de los datos de carácter personal, y quienes deberán adoptar las medidas técnicas descritas en el apartado de los presentes Términos y Condiciones de Uso. </p>
<p>PHARMALINK SL informa de la posibilidad de ejercer los derechos de acceso, rectificación, limitación de tratamiento, supresión, portabilidad y oposición al tratamiento, de los que el Usuario dispone y que pueden ser ejercitados ante PHARMALINK SL. De acuerdo con el Capítulo III del RGPD, debe tener en cuenta los siguientes matices: </p>
<p>- <strong>Derecho de Acceso:</strong> Es el derecho del usuario a obtener información sobre sus datos concretos de carácter personal y del tratamiento que se haya realizado o realice, así como de la información disponible sobre el origen de dichos datos y las comunicaciones realizadas o previstas de los mismos. </p>
<p>- <strong>Derecho de Rectificación:</strong> Es el derecho del afectado a que se modifiquen los datos que resulten ser inexactos o incompletos. Sólo podrá satisfacerse con relación a aquella información que se encuentre bajo el control de PHARMALINK SL, por ejemplo, eliminar comentarios publicados en la propia página, imágenes o contenidos web donde consten datos de carácter personal del usuario. </p>
<p>- <strong>Derecho a la Limitación de tratamiento:</strong> Es el derecho a que se limiten los fines del tratamiento previstos de forma original por el responsable del tratamiento. </p>
<p>- <strong>Derecho de Supresión:</strong> Es el derecho a suprimir los datos de carácter personal del usuario, a excepción de lo previsto en el propio RGPD o en otras normativas aplicables que determinen la obligatoriedad de la conservación de estos, en tiempo y forma. </p>
<p>- <strong>Derecho de portabilidad:</strong> El derecho a recibir los datos personales que el usuario, haya facilitado, en un formato estructurado, de uso común y lectura mecánica, y a transmitirlos a otro responsable. </p>
<p>- <strong>Derecho de Oposición:</strong> Es el derecho del usuario a que no se lleve a cabo el tratamiento de sus datos de carácter personal o se cese el tratamiento de estos por parte de PHARMALINK SL. </p>
<p>De acuerdo con los derechos que le confiere la normativa vigente en protección de datos podrá ejercer los derechos de acceso, rectificación, limitación de tratamiento, supresión, portabilidad y oposición al tratamiento de sus datos de carácter personal así como del consentimiento prestado para el tratamiento de los mismos, dirigiendo su petición a la dirección postal indicada más arriba o al correo electrónico info@ysana.es.   </p>
<p>Podrá dirigirse a la Autoridad de Control competente para presentar la reclamación que considere oportuna. </p>
<h1>Propiedad intelectual e industrial</h1>
<p>PHARMALINK SL por sí misma o como cesionaria, es titular de todos los derechos de propiedad intelectual e industrial de su página web, así como de los elementos contenidos en la misma (a título enunciativo, imágenes, sonido, audio, vídeo, software o textos; marcas o logotipos, combinaciones de colores, estructura y diseño, selección de materiales usados, programas de ordenador necesarios para su funcionamiento, acceso y uso, etc.), titularidad de PHARMALINK SL. Serán, por consiguiente, obras protegidas como propiedad intelectual por el ordenamiento jurídico español, siéndoles aplicables tanto la normativa española y comunitaria en este campo, como los tratados internacionales relativos a la materia y suscritos por España. </p>
<p>Todos los derechos reservados. En virtud de lo dispuesto en la Ley de Propiedad Intelectual, quedan expresamente prohibidas la reproducción, la distribución y la comunicación pública, incluida su modalidad de puesta a disposición, de la totalidad o parte de los contenidos de esta página web, con fines comerciales, en cualquier soporte y por cualquier medio técnico, sin la autorización de PHARMALINK SL. </p>
<p>El usuario se compromete a respetar los derechos de Propiedad Intelectual e Industrial titularidad de PHARMALINK SL. Podrá visualizar los elementos del portal e incluso imprimirlos, copiarlos y almacenarlos en el disco duro de su ordenador o en cualquier otro soporte físico siempre y cuando sea, única y exclusivamente, para su uso personal y privado. El usuario deberá abstenerse de suprimir, alterar, eludir o manipular cualquier dispositivo de protección o sistema de seguridad que estuviera instalado en las páginas de PHARMALINK SL. </p>
<h1>Acciones legales, legislación aplicable y jurisdicción</h1>
<p>PHARMALINK SL se reserva, asimismo, la facultad de presentar las acciones civiles o penales que considere oportunas por la utilización indebida de su sitio web y contenidos, o por el incumplimiento de las presentes condiciones. </p>
<p>La relación entre el usuario y el prestador se regirá por la normativa vigente y de aplicación en el territorio español. De surgir cualquier controversia las partes podrán someter sus conflictos a arbitraje o acudir a la jurisdicción ordinaria cumpliendo con las normas sobre jurisdicción y competencia al respecto. PHARMALINK SL tiene su domicilio en BARCELONA, España.</p>


