<?php

?>
<h1 class="ttl_general">PURCHASE TERMS AND CONDITIONS WWW.YSANA.ES</h1>
<span class="ttl_legal">Firstly, we thank you for buying at YSANA!</span>
<p class="txt_legal">This website is the responsibility of PHARMALINK SL, hereinafter PHARMALINK with number CIF · B62152335 and registered office in AV. UNIVERSITAT AUTÒNOMA, 13-PARC TECNOLÒGIC 08290, CERDANYOLA DEL VALLES (BARCELONA).</p>
<p class="txt_legal">All the data that you provide us will be governed by what our "privacy policy" indicates that you can consult at any time.</p>
<p class="txt_legal">We put at your disposal support service and customer service where we will solve all your doubts, on the phone number: +34 900 102 796. In addition, you can also make your inquiries by email at: info@ysana.es</p>
<span class="ttl_legal">Acceptance of the General Conditions.</span>
<p class="txt_legal">The placement of orders through our Web implies accepting the conditions of purchase. Thus, by checking the box that indicates these terms and conditions on our order forms, you accept without any exceptions of any kind these general conditions, which we detail and expand below:</p>
<span class="ttl_legal">Purchase and user registration</span>
<p class="txt_legal">Registering is the fastest way to access your orders and your information, as well as to receive information about future offers or promotions that we understand may be of your interest. However, in WWW.YSANA.ES you can place your order in several ways:</p>
<p class="txt_legal">If you choose the registration option, follow the following instructions:</p>
<p class="txt_legal">a) Select the "Login" icon located in the upper right part of our website.</p>
<p class="txt_legal">b) When selecting the "Login" link, you must register by clicking on the "Create your account" button.</p>
<p class="txt_legal">We will confirm your registration by sending you a welcome e-mail to the e-mail address that you have provided in the registration process. In this e-mail you will be informed that your account has been created.</p>
<p class="txt_legal">c) If you have previously registered, you can access your account from the registration icon or "Login", where in the "login" section you must enter your email and password.</p>
<p class="txt_legal">We remind you that the security of the username and password is your responsibility, so you must secure it properly, not communicating it to third parties.</p>
<p class="txt_legal">If you opt for the option of not registering:</p>
<p class="txt_legal">a) Add the desired products to the shopping cart. You can choose between continuing to add products: "See cart" or: "Proceed to checkout".</p>
<p class="txt_legal">b) Once you choose all the products you want, check them well and you will be able to process your order by clicking "Proceed to checkout"; if you are not registered you must do so at that time.</p>
<p class="txt_legal">c) On the ORDER screen you must enter the information that we request to process your order: Address or Shipping Address (you can add a different shipping address to the billing address)</p>
<p class="txt_legal">We will confirm your order by sending an e-mail to the e-mail address that you have provided us, where you will be informed of the details of your order.</p>
<span class="ttl_legal">Purchasing process</span>
<p class="txt_legal">Once the purchase is made, you can view and modify the steps related to the order described below:</p>
<span class="ttl_legal">Billing details</span>
<p class="txt_legal">In this section you can indicate the billing information of the order and modify them at any time before the order confirmation.</p>
<span class="ttl_legal">Shipment details.</span>
<p class="txt_legal">In this section you can indicate the delivery data of the order and modify them at any time before the order confirmation.</p>
<p class="txt_legal">We will inform you about any incident related to your order via the e-mail address that you have provided us. For this, it is essential that all the information you give us in your order is correct.</p>
<span class="ttl_legal">Shipping options and delivery times:</span>
<p class="txt_legal">The delivery of orders is made through Team Pharma SL. with CIF: B66868332, using our collaborator ASM messaging service.</p>
<p class="txt_legal">Shipping to Peninsula:</p>
<p class="txt_legal">Once the payment is confirmed for orders placed before 3pm, the delivery time is 24 working hours, for all our products that are normally in stock. The delivery date at the customer's address depends on the availability of the chosen product and the shipping area.</p>
<p class="txt_legal">Shipping to the Balearic Islands, Canary Islands, Ceuta and Melilla:</p>
<p class="txt_legal">Shipments to these destinations will be made by Post or by transport service. We recommend checking the cost of the shipment on: https://ysana.es/#form-contacto. Orders will be delivered to the Post Office or to the transport service the day after the payment confirmation.</p>
<p class="txt_legal">The delivery times that we have indicated are estimated delivery dates, depending on various factors that may vary depending on the characteristics of the order or on reasons beyond our control, difficulties in the delivery of the goods. (Number of products ordered, availability, festive season, volume, etc.).</p>
<p class="txt_legal">The shipments are only made to Peninsula, Balearic Islands, Canary Islands, Ceuta and Melilla. We regret to inform you that we do not send internationally.</p>
<p class="txt_legal">In general, all our orders will be processed and managed from Monday to Saturday. On Sundays and holidays, we do not offer a pick-up or delivery service.</p>
<p class="txt_legal">PHARMALINK cannot be held responsible if the information you provide us with during your purchase is inaccurate or incomplete or it is not possible to complete the delivery of the order due to the absence of the recipient or other reasons, such as restricted access to certain public buildings or similar situations. Although, PHARMALINK in order to satisfy our clients’ needs will always try to make the delivery possible.</p>
<p class="txt_legal">PHARMALINK cannot guarantee the delivery of your order at a specific time – but PHARMALINK will inform the transport company about your desired delivery schedule, however, we cannot assume any responsibility on the delivery times indicated by the buyer.</p>
<p class="txt_legal">There may be exceptional circumstances (Christmas period, transport strikes, weather or similar) so that shipments may suffer some delay.</p>
<span class="ttl_legal">Shipping costs</span>
<p class="txt_legal">Spain (Peninsula)</p>
<p class="txt_legal">Shipping costs are included free of charge in the final price of the product.</p>
<p class="txt_legal">Baleares, Canary Islands, Ceuta and Melilla:</p>
<p class="txt_legal">We recommend that you contact us via the form available at https://ysana.es/#form-contacto to verify the cost of your shipment.</p>
<p class="txt_legal">Before confirming your order, you will be informed about the shipping costs (for the Balearic Islands, Canary Islands, Ceuta and Melilla) and transport times, both guidelines, that apply to your specific order. However, both may vary depending on the specific circumstances.</p>
<p class="txt_legal">The shipping and delivery policies are subject to changes that will be reflected in this section or we will inform you before placing your order.</p>
<span class="ttl_legal">Payment Methods</span>
<p class="txt_legal">You can pay for all your purchases at WWW.YSANA.ES with your bank card.</p>
<span class="ttl_legal">Card payment</span>
<p class="txt_legal">The purchase cost will be charged to your bank account, usually immediately or within 24 hours from the date of the order and this action will be considered effective after the confirmation of payment to our bank.</p>
<p class="txt_legal">In the case of denial of payment notification stated by the POS (RedSys Point of Sale Terminal), the order will be automatically cancelled, informing you on-line or by email about the cancelation.</p>
<p class="txt_legal">The bank details entered are encrypted and transmitted securely to the bank's servers and then verified with the issuing bank to avoid possible fraud and abuse.</p>
<p class="txt_legal">Only the bank has the access to the bank details linked to these means of payment, so that PHARMALINK does not know or record this information during the payment transaction via POS.</p>
<span class="ttl_legal">Order confirmation</span>
<p class="txt_legal">Once the payment is confirmed, you will receive a confirmation email and we will start processing your order. Thank you for buying in "YSANA".</p>
<span class="ttl_legal">Cancellation of orders</span>
<p class="txt_legal">Once the payment has been made and confirmed, you will not be able to cancel your order.</p>
<span class="ttl_legal">Right of withdrawal or return articles</span>
<p class="txt_legal">Our products may be returned during the following 14 days from the date of delivery, in accordance with the conditions of the Spanish Retail Trade Law, provided that the product is in perfect condition, with its original packaging intact, documentation and accessories.</p>
<p class="txt_legal">In the case of wishing to return, you must inform PHARMALINK in writing at the following email: info@ysana.es indicating the number of your order and the reason why you wish to return it. In any case, PHARMALINK will authorize the return. PHARMALINK will assign you a return number and a shipping address will be provided.</p>
<p class="txt_legal">The transport costs originated by the return will be paid by the customer, that is, the material must be sent pre-paid by the client. Any material received freight collect will be rejected, as long as it was not an error of PHARMALINK at the time of processing the order.</p>
<p class="txt_legal">In no case the returns will be accepted without prior confirmation of PHARMALINK</p>
<p class="txt_legal">In no case, returns or exchanges will be accepted if the shipped product has been manipulated, unsealed, damaged or used.</p>
<p class="txt_legal">You should be responsible for the cost of the return except if you received a defective or damaged item.</p>
<p class="txt_legal">If the return fulfils all the conditions, the refund of the purchase according to the above will be made within a period of 14 days by the same means that the order was paid, not including the amount of the return shipping costs in the case that the reason for said return has not been caused by an error of PHARMALINK.</p>
<span class="ttl_legal">Return of damaged or defective items</span>
<p class="txt_legal">If you have received a defective or damaged item, you must notify us immediately upon receipt of the product, please contact us via e-mail or via phone. You will have 24 hours from receipt of the shipment to verify that your order has arrived correctly. After these 24 hours the shipment will be filed as confirmed and no claims will be accepted for defects or faults with the shipment.</p>
<p class="txt_legal">We recommend you checking and opening the package in the moment of the delivery. If you detect any anomaly, breakage or damage to the packaging or the product itself and consider that it is not acceptable, return it immediately to the delivery company, always indicating the reason on the delivery note that we provide, and we will contact you in order to solve the sooner the incidence.</p>
<p class="txt_legal">Returns will always be made in the same form of payment that you used for the purchase (Bank card)</p>
<p class="txt_legal">Except shipments of defective or damaged products, and within the deadlines established for this purpose, the shipping costs will never be subject to return.</p>

<span class="ttl_legal">Expiry Dates of the Products</span>
<p class="txt_legal">The original consumables have an expiration date established by the PHARMALINK laboratory.</p>
<p class="txt_legal">The customer should contact PHARMALINK via: info@ysana.es so that we can make the timely claim, also, the client must provide the invoice of the order. PHARMALINK will follow the action protocol under the condition that these defects or any other defects are from the factory and not the result of misuse or lack of maintenance by the customer.</p>

<span class="ttl_legal">Confidentiality commitment</span>
<p class="txt_legal">The User undertakes to maintain absolute confidentiality regarding the information contained in the invoices or communications sent by PHARMALINK, as well as the identity, address or contact details of PHARMALINK, the manufacturer of the products, the carrier or any other operator that intervenes in the chain of commercialization of the products, the technical or aesthetic characteristics of such products, their price, the conditions of payment and delivery of the same.</p>
<p class="txt_legal">All the aforementioned is excepted in the case that it is required by any governmental, judicial or regulatory authority, the total or partial delivery or disclosure of information and the Law does not allow its denial, in which case, and if the application of the law or a judicial order does not prevent it, the User must:</p>
<p class="txt_legal">1. Notify PHARMALINK in advance, in writing, specifying the information that has been required.</p>
<p class="txt_legal">2. Consult and cooperate with PHARMALINK in order to reach a conclusion about the advisability of initiating legal actions to avoid such requirement.</p>
<p class="txt_legal">3. Guarantee the confidential treatment of information. The User who breaches the duty of confidentiality to which he/she is bound by the acceptance of this commitment may incur a crime of disclosure of secrets, classified and punishable by articles 197 and following of the Penal Code.</p>
<span class="ttl_legal">Use and treatment of access codes</span>
<p class="txt_legal">The username and password that allow the User access to our website constitute confidential data and are exclusively personal and non-transferable. Therefore, the User is obliged not to communicate or provide his or her username or password to any third party or consent that they are used by any third party.</p>
<span class="ttl_legal">Incidents or claims</span>
<p class="txt_legal">In order to communicate any incident, complaint or query you can contact PHARMALINK at:</p>
<p class="txt_legal">Postal address: AV. UNIVERSITAT AUTÒNOMA, 13-PARC TECNOLÒGIC 08290, CERDANYOLA DEL VALLES (BARCELONA) SPAIN</p>
<p class="txt_legal">Email address: info@ysana.es</p>
<p class="txt_legal">Telephone +34 900 102 796</p>
<p class="txt_legal">These General Conditions may be subject to modifications, which will be communicated in this website. These General Conditions, as well as any other question related to the use and contracting will be governed by the provisions of Spanish legislation. Any dispute that may arise between the parties is submitted to the competent jurisdiction.</p>